# Generated by Django 3.1 on 2021-04-06 16:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210406_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
