# Generated by Django 3.1 on 2021-04-06 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_work_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es', models.CharField(max_length=255)),
                ('en', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.translate'),
        ),
    ]
